server:
  port: 0

spring:
  application:
    name: mcp-server-suivi-post

  main:
    web-application-type: none

  ai:
    mcp:
      server:
        name: mcp-server-suivi-post
        version: 0.0.1
        type: sync
        enabled: true
        stdio: true

app:
  api:
    url: https://www.laposte.fr/ssu/sun/back/suivi-unifie/{trackingNumber}
